team finished
jhhayashi/rn-devello pull request #6
Opened 2017-05-27 20:47 UTC by joshseides

working version

2017-05-27 21:11 UTC, jhhayashi commented on components/Board/index.js
> +        this.state = { lists: [{
indentation is messed up here

2017-05-27 21:28 UTC, jhhayashi requested changes

2017-05-27 21:28 UTC, jhhayashi commented on components/Board/index.js
> +                <Text>{this.props.name}</Text>
use a `propTypes` static property property

2017-05-27 21:28 UTC, jhhayashi commented on components/Board/index.js
> +                    {this.state.lists.map((l, i) => <List title={l.title} cards={l.cards} key={i}/>)}
could use the spread operator here

2017-05-27 21:28 UTC, jhhayashi commented on components/Board/index.js
> +                    {this.state.lists.map((l, i) => <List title={l.title} cards={l.cards} key={i}/>)}
using the array index as the key here is dangerous. prob better to use the list name, and mandate that they're all different

2017-05-27 21:28 UTC, jhhayashi commented on components/Board/index.js
> +    render() {
convention is to declare the render function as the last method

2017-05-27 21:28 UTC, jhhayashi commented on components/Board/index.js
> +        let index = -1;
no need to initialize this.

```javascript
let index;

// later
if (!index) throw new Error('invalid id')
```

2017-05-27 21:28 UTC, jhhayashi commented on components/Board/index.js
> +            return {
```javascript
let newLists = this.state.lists.map((list, i) => ({
  ...list,
  cards: list.cards.filter(e => {

```

2017-05-27 21:28 UTC, jhhayashi commented on components/Board/index.js
> +        if ((index + dir) < 0 || (index + dir) >= this.state.lists.length) throw new Error ('you illegal with your move');
this line is too long

2017-05-27 21:28 UTC, jhhayashi commented on components/Board/index.js
> +                    title: l.title,
using the spread operator here is actually safer (in case you add keys to the lists and forget to include them here)

2017-05-27 21:28 UTC, jhhayashi commented on components/Board/index.js
> +                cards: l.cards.filter(e => e.id !== id)
`e` is not a good variable name here

2017-05-27 21:28 UTC, jhhayashi commented on components/Board/index.js
> +                title: l.title,
spread operator here too

2017-05-27 21:28 UTC, jhhayashi commented on components/Board/index.js
> +        let newLists = this.state.lists.map(l => {
this is all done destructively. if so, no need to store `newLists` (you never use it) or use the `map()` function. use `forEach()`

2017-05-27 21:28 UTC, jhhayashi commented on components/Button/index.js
> +        text: PropTypes.string,
see my comments in your merge request

2017-05-27 21:28 UTC, jhhayashi commented on components/List/index.js
> +        display: 'flex',
no need to do this in react-native. it's the default

2017-05-27 21:28 UTC, jhhayashi commented on main.js
> +    paddingTop: Constants.statusBarHeight,
nice!

2017-05-27 21:28 UTC, jhhayashi commented on main.js
> +import Button from './components/Button';
don't think you need `Button`, `Card`, or `List`

2017-05-28 03:26 UTC, joshseides commented
code updated for comments

2017-05-28 15:03 UTC, jhhayashi commented on components/Board/index.js
> +            lists: this.state.lists.map(l => {
This won't work

```javascript
this.setState({
  lists: this.state.lists.map(list => ({
    ...list,
    cards: list.cards.map(card => ({
      ...card,
      moveForward: this.moveForward.bind(null, card.id),
      moveBackward: this.moveBackward.bind(null, card.id),
      delete: this.deleteCard.bind(null, card.id),
    })
  })
})
```

2017-05-28 15:09 UTC, jhhayashi approved these changes

2017-05-28 15:09 UTC, merged